//User
export const GET_USERS = 'GET_USERS'
export const GET_PROFILE = 'GET_PROFILE'
//Product
export const GET_PRODUCTS = 'GET_PRODUCTS'

export const ESTADO_ACTION_TYPES = {
  GET_ESTADOS: 'GET_ESTADOS',
  GET_ESTADO: 'GET_ESTADO',
  ADD_ESTADO: 'ADD_ESTADO',
  UPDATE_ESTADO: 'UPDATE_ESTADO',
  DELETE_ESTADO: 'DELETE_ESTADO'
}

export const CATEGORY_ACTION_TYPES = {
  GET_CATEGORYS: 'GET_CATEGORYS',
  GET_CATEGORY: 'GET_CATEGORY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY'
}

export const ORDEN_ACTION_TYPES ={
  GET_ORDENES: 'GET_ORDENES',
  GET_ORDEN: 'GET_ORDEN',
  ADD_ORDEN: 'ADD_ORDEN',
  UPDATE_STATE_ORDEN: 'UPDATE_STATE_ORDEN'
}

export const CLIENT_ACTION_TYPES ={
  GET_CLIENTS: 'GET_CLIENTS',
  GET_CLIENT: 'GET_CLIENT'
}

export const CART_ACTION_TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_CART: 'CLEAR_CART'
  }

export const AUTH_ACTION_TYPE ={
    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGOUT: 'LOGOUT'
}
